### ISSUE TITLE
Handle "A" %>% setNames(.) and similar

### ISSUE THREAD

**Issue by franknarf1** [smbache/magrittr#128]
Intuitively, I expect this to work, since `.` goes into the first argument and whatever I pass in `()` goes into the second argument. My workaround is `"A" %>% setNames(., .)`.

I'm doing this to give labels to the results of an `lapply` call, like

    DF = data.frame(id = sample(LETTERS, 100, TRUE), stringsAsFactors=FALSE)
    lapply(unique(DF$id) %>% setNames(.,.), nchar)

Maybe there's some cleaner way to approach that.

**Comment by kdirek** [comment]
You can avoid the pipe with sapply:

`sapply(unique(DF$id), nchar, simplify = FALSE, USE.NAMES = TRUE)`

**Comment by smbache** [comment]
True, but some more "realistic" cases do occur. In any case, the rule used by `%>%` is that if there are no dots in the rhs call, then it will be placed as the first argument, otherwise the dot(s) will be used. Nested dots, do not count, and this makes the cleanest code in most situations, e.g. 

```
result <-
  mtcars  %>% 
  transform(car = rownames(.)) %>% 
  set_rownames(NULL)
```

In the above call to `transform` there is only a nested dot, and `mtcars` is still placed as first argument. 
This is cleaner than having to place two dots just because you need to use an attribute of the left-hand side (here, the row names).

There are of course examples, where this rule may seem less meaningful, but they don't come close to outweighing the benefits, since when LHS is used more than once in the RHS, it is to use an attribute (in a general sense) and not for a "main purpose".

You can "nest" the dot, in which case LHS will be added as first argument too: `value %>% setNames((.))`, although this is not that expressive either. 

I tend to add verbs to clarify the code when these situtations occur:

```
self_name <- function(x) setNames(x, x)
...
unique(DF$id) %>% self_name
...
```
Although, as @kdirek mentions, there is a simple non-pipe solution in your case.

**Comment by franknarf1** [comment]
Thanks for the replies. I didn't realize `sapply` would take values as names. That resolves my only use-case. I also like the "nested" dot approach `%>% setNames((.))`, and will probably use that if/when I come across this issue again. 

I'm closing since, if I understand you correctly, tweaking to cover this case would mess up things in many other situation.

**Comment by smbache** [comment]
As a side note, I'd recommend using `vapply` rather than `sapply` as it is strict and more safe.
