### ISSUE TITLE
standard evaluation pipe

### ISSUE THREAD

**Issue by davharris** [smbache/magrittr#87]
This may not be news or interesting, but I thought I'd post it here just in case.  Sorry if it's not.

In response to a [challenge](https://twitter.com/noamross/status/603802615181279232) from @noamross, I made a "pipe" that doesn't do non-standard evaluation (unless `do.call` counts as non-standard?).  Many R users avoid non-standard methods, and so I thought that something like this might appease them.

The new pipe takes a list as its second argument.  The first element of the list is the function to be applied, and the rest of it contains additional arguments.

```
`%_%` = function(x, flist){
  do.call(flist[[1]], c(list(x), flist[-1, drop = FALSE]))
}
```

Example usage:

```
# Log-transform the cars data set and plot it with filled red points
cars %_% list(log) %_% list(plot, col = 2, pch = 16)
```

I haven't really tested this, and I'm sure there are cases where `%>%` will work much better. But I thought that something like it might help pipes get more acceptance, and I'd be interested to hear what you think.

**Comment by daattali** [comment]
That was fast work since the discussion!

It's definitely a nice idea and it's be great if we can have SE pipes. But do you think there could be SE versions of most pipes and the cool functionalities they have? Like `%<>%`, `%T>%`, `%$%`, `%>% {}`

Also, how would you do something like `mtcars %>% .[['wt']]` using `%_%`?

(I realize you only worked on this for 5 minutes and probably don't have answers at this moment, just points for discussion)

**Comment by smbache** [comment]
Can anyone give a real-life example that merits working on this? I mean, I have worked *a lot* with pipes in and out of packages, and I have not really had any issues. Maybe I've been lucky, I'm asking because I don't realize why it would be important... I am guessing also that many people have been using it through `dplyr`, `rvest`, etc, even in pkgs, and we have not yet had a convincing issue about this.

**Comment by davharris** [comment]
@smbache You could very well be right. I was taking other folks' concerns at face value.  Sorry if this turns out to be a solution in search of a problem.

@daattali I suspect that the other pipes would require ugly workarounds at best, but I'm not sure.

**Comment by daattali** [comment]
TBH I personally am not against using pipes in my packages because it makes code infinitely cleaner and more readable.  And I can't think of how it could cause problems. But there is a fairly widely-accepted notion of trying to minimize the use of NSE functions in packages, and I think that alone deters people from using `%>%` in packages.  I admit I don't quite understand how this particular function could bite us back (and it never had yet), but I was just thinking it would be nice to have SE so that everyone would use it without any worry.  Maybe that's not enough reason to spend so much effort though :)

**Comment by smbache** [comment]
Maybe @hadley , with his expertise from writing AdvR, has some kind of useful insight? Maybe it's a phantom problem...

**Comment by hadley** [comment]
I'm most concerned with NSE in this situation:

```R
my_fun <- function(df) {
  with(df, x + y)
}
```

because if the data frame doesn't have x and y variables, you might not get an error if you have `x` and `y` defined elsewhere (or you might get an error that is completely uninformative).

I tend to avoid magrittr pipes in functions, but I don't think it's a strong rule. I tend to avoid them because I think pipes tend to give slightly less informative messages (which is fine when working interactively, but makes life slightly harder when writing a function). That said, I don't tend to write functions that have either long pipelines of transformations or deeply nested function compositions, so choosing not to use `%>%` doesn't make much impact on the majority of my code.

**Comment by smbache** [comment]
Indeed, but this concern is not really a concern with piping, right?

**Comment by hadley** [comment]
Right, and a standard evaluation pipe doesn't fix my concern.

**Comment by smbache** [comment]
OK; so I think we close this "issue" for now, and if anyone has a reasonable example or argument then we can always re-open this.

**Comment by davharris** [comment]
Fair enough. Have a good day. 

Dave

**Comment by smbache** [comment]
Likewise. And thanks for taking the time to think about it. I appreciate it although I'm not (yet) convinced action is necessary.
