### ISSUE TITLE
Possible bug: using %>% with stop()

### ISSUE THREAD

**Issue by Mullefa** [smbache/magrittr#93]
Is the following a bug?

```R
recover_with <- function(x, y) tryCatch(x, error = function(e) y)

# OK
recover_with(stop(), 1)

# not OK
stop() %>% recover_with(1)
```

**Comment by smbache** [comment]
`%>%` is eager, so will evaluate lhs before inserting into rhs. Not a bug, just not possible.

**Comment by smbache** [comment]
The way it's implemented, that is. May be possible with a different approach to piping

**Comment by Mullefa** [comment]
Ah ok, thanks for clarifying. Not sure if the demand is there, but it would be kinda neat if there were two pipe operators which allowed for passing by value (`%>%`), and passing by name (not currently implemented) respectively.

**Comment by Mullefa** [comment]
Btw I think #80 is caused by `%>%` being eager too.

**Comment by smbache** [comment]
I think it is beyond the scope of magrittr and would only complicate matters more than it would be beneficial, IMO.

**Comment by smbache** [comment]
Currently the NS evaluation of magrittr is (to my knowledge) quite harmless. Having the kind of NS you're suggesting could open up a can of worms ;)

**Comment by Mullefa** [comment]
I think its completely reasonable if you don't want to include it in the package - I don't have a convincing case either way, so feel free to close this issue if you want.

As an aside, in the spirit of expanding my knowledge, why would this open up a can of worms? Isn't this more akin to how R would evaluate a function call?

**Comment by smbache** [comment]
My point is just that more complexity will add a non-negative amount of trouble ;-)

Here's one example:

```R
some_data %>% 
  some_time_consuming_task %>% 
  head(1:(NROW(.) %/% 2))
```

Here LHS is used twice (once as the data itself, and also to inspect the number of rows in the result), and one  should not let R lazily evaluate the (possibly long and combined) LHS more than once. In some sense `%>%` is "linearizing" otherwise non-linear workflow that way. And I bet down the road one would run into many such problems, but this is mostly speculating.

Also, debugging (which is already an achilles heel) I suspect would become more difficult.
